import type { Deal } from './crm-utils'

/** Local-only sample rows so the dashboard can be previewed without auth. */
export const PREVIEW_DEALS: Deal[] = [
  {
    id: 'preview-1',
    owner_name: 'James R. Holcomb',
    tract_abstract: 'A-142',
    operator_name: 'Diamondback E&P',
    county: 'howard',
    mailing_city: 'Big Spring',
    mailing_state: 'TX',
    acreage: 160,
    monthly_royalty: 4200,
    tag: 'hot',
    follow_up_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    phone: '4325550198',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'preview-2',
    owner_name: 'Martha E. Voss Trust',
    tract_abstract: 'A-88',
    operator_name: 'Apache Corporation',
    county: 'martin',
    mailing_city: 'Stanton',
    mailing_state: 'TX',
    acreage: 80,
    monthly_royalty: 1800,
    tag: 'interested',
    follow_up_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    email: 'trustee@example.com',
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'preview-3',
    owner_name: 'Pecos Mineral Holdings LLC',
    tract_abstract: 'A-210',
    operator_name: 'SM Energy',
    county: 'midland',
    mailing_city: 'Midland',
    mailing_state: 'TX',
    acreage: 240,
    monthly_royalty: 9100,
    tag: 'offer_sent',
    offer_amount: 185000,
    follow_up_date: new Date(Date.now() + 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'preview-4',
    owner_name: 'Linda Kay Pruitt',
    tract_abstract: 'A-55',
    operator_name: 'Pioneer Natural Res.',
    county: 'midland',
    mailing_city: 'Odessa',
    mailing_state: 'TX',
    acreage: 40,
    tag: 'prospect',
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'preview-5',
    owner_name: 'Robert N. Salinas',
    tract_abstract: 'A-19',
    operator_name: 'Occidental Permian',
    county: 'loving',
    mailing_city: 'Mentone',
    mailing_state: 'TX',
    acreage: 120,
    monthly_royalty: 2600,
    tag: 'skip_traced',
    phone: '4325550144',
    phones: ['4325550144', '4325550188'],
    email: 'rsalinas@example.com',
    follow_up_date: new Date().toISOString(),
    connected_phone: '4325550144',
    phone_activity: {
      '4325550144': {
        lastCalledAt: new Date(Date.now() - 3600000).toISOString(),
        lastOutcome: 'connected',
        lastCalledByName: 'Josh',
        connected: true,
      },
      '4325550188': {
        lastCalledAt: new Date(Date.now() - 86400000).toISOString(),
        lastOutcome: 'voicemail',
        lastCalledByName: 'Josh',
      },
    },
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'preview-6',
    owner_name: 'Helen M. Cartwright',
    tract_abstract: 'A-301',
    operator_name: 'HighPeak Energy',
    county: 'howard',
    mailing_city: 'Coahoma',
    mailing_state: 'TX',
    acreage: 20,
    tag: 'call_back',
    follow_up_date: new Date(Date.now() + 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'preview-7',
    owner_name: 'Westfork Royalty Partners',
    tract_abstract: 'A-77',
    operator_name: 'Vital Energy',
    county: 'upton',
    mailing_city: 'Dallas',
    mailing_state: 'TX',
    acreage: 320,
    monthly_royalty: 15000,
    tag: 'closed_won',
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'preview-8',
    owner_name: 'Lila J. Pennington',
    tract_abstract: 'A-54',
    operator_name: 'Pioneer Natural Resources',
    county: 'midland',
    mailing_city: 'Odessa',
    mailing_state: 'TX',
    acreage: 640,
    tag: 'skip_traced',
    source: 'skip_trace',
    needs_phone: true,
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
]

export const shouldLoadPreviewDeals = (): boolean => {
  if (process.env.NODE_ENV === 'production') return false
  if (typeof window === 'undefined') return false
  return new URLSearchParams(window.location.search).get('preview') === '1'
}
